# Generated by Django 3.2.7 on 2022-04-17 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('codice_fiscale', models.CharField(max_length=16)),
                ('business_name', models.CharField(max_length=220)),
                ('vat_number', models.CharField(max_length=11)),
                ('is_pharmacist', models.BooleanField(default=False)),
                ('license_number', models.CharField(max_length=10, null=True)),
                ('chat_online', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('blockchain_address', models.CharField(default='', max_length=42)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sellers',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('codice_fiscale', models.CharField(max_length=16)),
                ('chat_online', models.BooleanField(default=False)),
                ('blockchain_address', models.CharField(default='', max_length=42)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=5)),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.IntegerField()),
                ('further_info', models.TextField(blank=True, default=None, null=True)),
                ('is_billing', models.BooleanField(default=False)),
                ('is_shipping', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.customer')),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
    ]
