# Generated by Django 3.2.7 on 2022-04-17 19:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSubstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'activeSubstances',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='accounts.customer')),
            ],
            options={
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(default=None, max_length=80)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('standard_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('website_url', models.CharField(max_length=2048, null=True)),
            ],
            options={
                'db_table': 'couriers',
            },
        ),
        migrations.CreateModel(
            name='Excipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'excipients',
            },
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'illnesses',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_vat_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('dosage', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('vat_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('available_quantity', models.IntegerField()),
                ('is_sponsored', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'statuses',
            },
        ),
        migrations.CreateModel(
            name='SponsoredPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsorship_fee_percentage', models.DecimalField(decimal_places=2, default=10, max_digits=20)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_package', to='shop.package')),
            ],
            options={
                'db_table': 'sponsoredPackages',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tracking_code', models.CharField(max_length=50, null=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier', to='shop.courier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='shop.order')),
            ],
            options={
                'db_table': 'shipments',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aic', models.CharField(max_length=9, null=True)),
                ('description', models.TextField()),
                ('needs_prescription', models.BooleanField(default=False)),
                ('slug', models.SlugField(default=None, max_length=160)),
                ('has_sponsor', models.BooleanField(default=False)),
                ('active_substance', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.activesubstance')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
                ('excipients', models.ManyToManyField(default=None, related_name='excipients_products', to='shop.Excipient')),
                ('illnesses', models.ManyToManyField(default=None, related_name='illnesses_products', to='shop.Illness')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='PackageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('vat_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('is_sponsored', models.BooleanField(default=False)),
                ('sponsorship_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('is_discounted', models.BooleanField(default=False)),
                ('coupon', models.TextField(default=None, null=True)),
                ('coupon_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages_orders_orders', to='shop.order')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages_orders_packages', to='shop.package')),
            ],
            options={
                'db_table': 'packages_orders',
            },
        ),
        migrations.CreateModel(
            name='PackageCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages_carts_carts', to='shop.cart')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages_carts_packages', to='shop.package')),
            ],
            options={
                'db_table': 'packages_carts',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='shop.product'),
        ),
        migrations.AddField(
            model_name='package',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='accounts.seller'),
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_address', models.TextField()),
                ('further_info', models.TextField(blank=True, default=None, null=True)),
                ('is_shipping', models.BooleanField()),
                ('is_billing', models.BooleanField()),
                ('address', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.address')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.order')),
            ],
            options={
                'db_table': 'orders_addresses',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ManyToManyField(related_name='addresses_orders', through='shop.OrderAddress', to='accounts.Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='package',
            field=models.ManyToManyField(related_name='packages_orders', through='shop.PackageOrder', to='shop.Package'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.seller'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.status'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=None, upload_to='products')),
                ('is_main', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('comment', models.TextField(null=True)),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='shop.order')),
            ],
            options={
                'db_table': 'feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(default=None, null=True)),
                ('is_discounted', models.BooleanField(default=False)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('usable', models.BooleanField(default=False)),
                ('chat', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='chat.chat')),
            ],
            options={
                'db_table': 'coupons',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='package',
            field=models.ManyToManyField(related_name='packages_carts', through='shop.PackageCart', to='shop.Package'),
        ),
    ]
